LLM_MODEL = "qwen2.5:7b"
EMBEDDING_MODEL = "embeddinggemma:latest"
TOKENIZER_MODEL = "Qwen/Qwen2.5-7B"

DOCUMENT_DIRECTORY = "documents"

CHUNK_SIZE = 100
CHUNK_OVERLAP = 20
SIMILARITY_THRESHOLD = 0.4